### ISSUE TITLE
Support logging to syslog/file

### ISSUE THREAD

**Issue by ananace** [adrienthebo/r10k#1230]
## Use Case

When triggering R10k deployments from remote scripts or pipelines, there's no supported method to locally see the output if something fails.

## Describe the Solution You Would Like

Adding support for specifying that R10k should output logging onto syslog or to a file either instead of _or_ in addition to stdout would allow for a local sysadmin to read through the logs from a triggered run.

## Describe Alternatives You've Considered

Creating local wrappers that pipe r10k output into syslog or file could be used, though it would require either owning every location where a call could occur from, or by replacing all r10k binaries with wrappers.

**Comment by mwaggett** [comment]
hey @ananace thanks for opening this! Unfortunately, it's not likely that we will get to this feature, since we have no use for it internally, but we're happy to review and help with a PR if you wanted to implement this feature yourself!
