### ISSUE TITLE
Remove "bare" environment type

### ISSUE THREAD

**Issue by reidmv** [adrienthebo/r10k#1235]
The "bare" environment type was renamed to "plain", but the original name was left in place (with a deprecation warning) for backwards compatibility until the 4.0 release.

Remove the "bare" environment type entirely for the 4.0 release.

**Comment by mwaggett** [comment]
opened in JIRA here: https://tickets.puppetlabs.com/browse/RK-386

**Comment by Magisus** [comment]
PR for this https://github.com/puppetlabs/r10k/pull/1253
