### ISSUE TITLE
Make it possible to exclude modules or ignore errors

### ISSUE THREAD

**Issue by baurmatt** [adrienthebo/r10k#1248]
## Use Case
We're making heavy usage of CI to ensure that our control repository is well tested and bugs are catched before rolled out in production. For this we're deploying the Puppetfile in the CI with r10k with `r10k puppetfile install`. This works fine but requires the CI to have access to all modules including hieradata.

As hieradata might contain "secrets" we would prefer to not deploy it in the CI especially since it isn't actually used in the CI. CI for hieradata itself is handled separately.

## Describe the Solution You Would Like
I see to options to makes this possible:

1. Add an option `--ignore-errors`

This would need to be wrapped around this line:
https://github.com/puppetlabs/r10k/blob/120d7e3b2a879013b98af931eb58fe946adbd358/lib/r10k/content_synchronizer.rb#L47

2. Add an option `--exclude-module=xyz`

This would exclude the give module from deployment. It should be possible to add this option several times.

## Describe Alternatives You've Considered

I've hacked locally and verified that solution 1 works.

Currently we're just sedding the module out of the Puppetfile:

Puppetfile:
```
mod 'hieradata',
  :git            => 'git@gitlab.internal.org:puppet/hieradata.git',
  :branch         => :control_branch,
  :default_branch => 'master',
  :install_path   => 'hieradata'
...
```

Removed with:
```
sed -i -e '/mod.*hieradata/,+4d' Puppetfile
```

**Comment by baurmatt** [comment]
Still interested to get this feature in r10k :)

**Comment by baurmatt** [comment]
Yep, still important to me.

/me against the bot.

**Comment by Magisus** [comment]
Tagged it so that won't happen anymore. Sorry, we're having very little time to invest in this project at the moment. However, we're still definitely accepting PRs, if you'd like to submit something. I think I have a slight preference for option 2, but if you have option 1 working, feel free to put it up and we can take a look.
