### ISSUE TITLE
r10k puppetfile install always runs "force" mode

### ISSUE THREAD

**Issue by otterz** [adrienthebo/r10k#1265]
## Describe the Bug
`r10k puppetfile install ...` always runs in force mode, no matter if `--force` flag is set or not. With this all local modifications will be overwritten by r10k.

## Expected Behavior
Refering to the documention, r10k should not overwrite local modifications by default, so I expect modules with local modifications to be skipped from sync.

## Steps to Reproduce
1. Modify a local modul
2. Run `r10k puppetfile install --verbose=notice`

## Environment
 - 3.14.0 (installed via puppet gem)
 - CentOS7

## Additional Context
I'm updating from 3.8.0 to 3.14.0.

After some quick debugging I guess [this](https://github.com/puppetlabs/r10k/blob/e032473cee6948d7ba1e072ed8e098d1c8e5be32/lib/r10k/module/git.rb#L70) is the cause. `@overrides.dig(:modules, :force)` returns `nil` because the key `:modules` does not exists in `@overrides` Hash when using r10k puppetfile install. So force is nil and @force will be set to true.

**Comment by Magisus** [comment]
This should be resolved by https://github.com/puppetlabs/r10k/pull/1269

**Comment by mwaggett** [comment]
released in 3.14.1
