### ISSUE TITLE
Require docker image for ARM64 platform

### ISSUE THREAD

**Issue by odidev** [adrienthebo/r10k#1276]
Hi Team,

I am trying to use the **r10k**  image on  arm64  platform, but it seems it is not available for arm64.

I have successfully built the image for arm64 platform, using the command  `docker build -t image_name .`

I have modified the **Makefile** and **.github/workflows/docker.yml** files to release the docker image of **puppetlabs/r10k** for both the platforms using buildx.

**Commit Link** - https://github.com/odidev/r10k/commit/0e644987e1348a5d23d95168a30703905fb2a383

**Docker Hub Link** - https://hub.docker.com/repository/docker/odidev/r10k/tags?page=1&ordering=last_updated

Do you have any plans for releasing ARM64 images?

If interested, I will raise a PR with the above changes.

**Comment by mwaggett** [comment]
hey @odidev ! Feel free to open a PR and we'll take a look! Thanks!

**Comment by mwaggett** [comment]
PR: https://github.com/puppetlabs/r10k/pull/1282
