### ISSUE TITLE
environment_name is undocumented

### ISSUE THREAD

**Issue by gdubicki** [adrienthebo/r10k#1281]
Current stable r10k warns me on start:
```
WARN     -> "basedir" is deprecated. Please use "environment_name" instead. "basedir" will be removed in a future version.
```
...but I haven't found info in the docs how to use `environment_name`.

I tried just replacing `basedir` with `environment_name` but it results in an error:
```
# r10k deploy module -e qa hiera -v
ERROR    -> no implicit conversion of nil into String
```

**Comment by mwaggett** [comment]
Thanks for opening this @gdubicki ! We'll try to get this documented soon. 😊

**Comment by gdubicki** [comment]
Thanks @mwaggett! I assume that creating a proper doc update is a more time-consuming task that you need to plan, but perhaps you can at least quickly and informally write here how can I (and other people affected) get rid of this warning?

**Comment by gdubicki** [comment]
Please reopen. This has not been resolved.

**Comment by gdubicki** [comment]
Still not resolved.
