### ISSUE TITLE
Tarball module content will be unpacked  into an subdirectory with tarball name

### ISSUE THREAD

**Issue by ze6ra** [adrienthebo/r10k#1290]
## Describe the Bug
When install  module with '**tarball**' type module content  unpacked into an subdirectory with tarball name.
In Puppetfile:
mod 'puppet-chrony',
        type: 'tarball',
        source: 'http://########/forge/puppet/chrony/puppet-chrony-2.1.0.tar.gz'

After deploy:
 tree -d ./modules/chrony/
./modules/chrony/
└── puppet-chrony-2.1.0
    ├── examples
    ├── functions
    ├── manifests
    ├── templates
    └── types

## Expected Behavior
Tarball module content will be unpacked directly into an appropriately named module directory chrony without subdirectory  puppet-chrony-2.1.0.

## Steps to Reproduce
1. Make Puppetfile with content:
mod 'puppet-chrony',
        type: 'tarball',
        source: 'http://########/forge/puppet/chrony/puppet-chrony-2.1.0.tar.gz'
2. /opt/puppetlabs/puppet/bin/r10k  puppetfile install
3. tree -d ./modules/chrony/

## Environment
 - Version r10k 3.14.2
 - Platform RHEL8

**Comment by reidmv** [comment]
I think this would be addressed by #1285
