### ISSUE TITLE
r10k gem fails to install on windows without admin or Create symbolic links user rights

### ISSUE THREAD

**Issue by davidsandilands** [adrienthebo/r10k#1316]
## Describe the Bug
When installing the r10kgem on a windows system without adminstrator or symlink permissions the following error appears 
Errno::EACCES: Permission denied @ rb_file_s_symlink - (../expected_1,

As r10k gem is a requirement of PDK this stops installation of pdk on corporate windows dev systems without admin/permissions.

## Expected Behavior
The gem should install

## Steps to Reproduce
gem install r10k

## Environment
 - Version 3.11 and above
 - Platform Windows 10/11, Windows Server 2021

## Additional Context
https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links

**Comment by davidsandilands** [comment]
Completed with merged PR

**Comment by davidsandilands** [comment]
PR merged closing issue

**Comment by mwaggett** [comment]
Resolved by https://github.com/puppetlabs/r10k/pull/1315 and released in r10k 3.15.1.
