### ISSUE TITLE
R10k should be able to use bare Git repository without authentication as conrol_repo

### ISSUE THREAD

**Issue by cvquesty** [adrienthebo/r10k#1317]
## Use Case
Many clients are beginning to disable SSH on their corporate Git repositories in favor of Oauth tokens. R10k should support bare git without authentication to support this configurtion.

## Describe the Solution You Would Like
That R10k could be pointed at a control repo with an oauth token as its source, and not use SSH keys.  URL format is:

https://oauth2:<oauthtoken>@gitserver.foo.com/path/to/control_repo.git

## Describe Alternatives You've Considered
This is new functionality to meet emerging Infosec trends and practices

## Additional Context
Currently, the Puppetfile can reference these URLs because there is no prohibition to just referencing a bare repo:

mod 'foo',
  :git        => 'https://oauth2:<oauthtoken>@gitserver.foo.com/path/to/modulename.git,
  :branch => 'production'

Similarly, the specification of the control repo should be able to be done in the Puppet Console and/or the r10k.yaml, and NOT need an SSH key to do the reads of the control_repo.

**Comment by binford2k** [comment]
What happens if you specify `:git => 'https://<token>/:@gitserver.foo.com/path/to/modulename.git` now?

**Comment by cvquesty** [comment]
Keep in mind, we're talking about the control_repo URL that gets placed into r10k.yaml (or in the console in PE)

Neither mechanism seems to know what to do with the tokenized HTTPS for r10k/Code Manager.

**Comment by cvquesty** [comment]
Specifically the control_repo.  This is prior to the Puppetfile

**Comment by mwaggett** [comment]
Hi @cvquesty, thanks for opening this! r10k is now considered to be feature complete and we are unfortunately discontinuing development. As a result, we are closing all open issues and pull requests. I sincerely apologize that we’re unable to address this issue.
