### ISSUE TITLE
R10k container - cannot generate types (missing puppet binary)

### ISSUE THREAD

**Issue by shaun-rutherford** [adrienthebo/r10k#1322]
## Describe the Bug
Using the r10k container with the generate types flag or the generate types configuration option produces the following error message:
```
[2022-11-02 13:40:19 - ERROR] Command exited with non-zero exit code:
Command: /opt/puppetlabs/bin/puppet generate types --environment jenkins --environmentpath /etc/puppetlabs/code/environments --config /etc/puppetlabs/puppet/puppet.conf
Stderr:
Errno::ENOENT: No such file or directory - /opt/puppetlabs/bin/puppet
Exit code: 254
```

## Expected Behavior
The generate types command should complete and exit with a 0 status code

## Steps to Reproduce
1. Run the r10k docker container with the --generate-types flag or with a custom r10k.yaml config file with the generate types key value pair set

## Environment
 - Version 3.8.0 and 3.15.2
 - Platform Docker (Ubuntu and CentOS host)

## Additional Context
Example config file I'm running:
git:
  provider: rugged
  private_key: /etc/pki/tls/private/control-repo-private-key

deploy:
  generate_types: true

sources:
  puppet:
    basedir: /etc/puppetlabs/code/environments
    remote: <remove host here>

Example command running:
docker container run -v puppet_puppet-code:/etc/puppetlabs/code -v /etc/pki/tls/private/control-repo-private-key:/etc/pki/tls/private/control-repo-private-key puppet/r10k:3.8.0 --color --verbose=debug -c /etc/puppetlabs/code/r10k.yaml deploy environment jenkins

**Comment by mwaggett** [comment]
Hi @shaun-rutherford, thanks for opening this! r10k is now considered to be feature complete and we are unfortunately discontinuing development. As a result, we are closing all open issues and pull requests. I sincerely apologize that we’re unable to address this issue.
