### ISSUE TITLE
Not sure about the hiera.yaml statement in common-patterns

### ISSUE THREAD

**Issue by lesinigo** [adrienthebo/r10k#1350]
The [current `common-patterns.md`](https://github.com/puppetlabs/r10k/blob/72526e0ba526f103c3fa307f78a03424862f398a/doc/common-patterns.mkd) states:

> Use a [Control Repo](https://docs.puppet.com/pe/latest/cmgmt_control_repo.html) to store your Puppetfile.
> Hiera data should be in the Control repo OR as a separate source in r10k.yaml. **_Any hiera.yaml in the Control repo will be ignored on a per environment basis, locating it at /etc/puppetlabs/puppet/hiera.yaml is prefered._**
> Each puppet module should be contained in its own independent forge module or repository.

It may be me, but I'm not understanding the part in bold, it seems to contradict the [official Puppet documentation](https://www.puppet.com/docs/puppet/8/hiera_config_yaml_5.html#hiera_config_yaml_location-title-1538585369054) that clearly says that Hiera will use (among others) any per-environment `hiera.yaml` that it gets.

That file is 6 years old, could it be that it was referring to some older version of Puppet and it is now wrong?
Do we need to fix the documentation or is there something else that I'm missing?

**Comment by justinstoller** [comment]
Yes, the documentation is outdated. Thanks for the heads up, @lesinigo ! I'll fix shortly.

**Comment by justinstoller** [comment]
Closing this as there's now PR open to track resolving.
