### ISSUE TITLE
r10k gem is not compatible with faraday 2.9.0

### ISSUE THREAD

**Issue by vchepkov** [adrienthebo/r10k#1370]
Attempts to install r10k with puppet 7 gem fail 

```
The last version of faraday (~> 2.0) to support your Ruby & RubyGems was 2.8.1. Try installing it with `gem install faraday -v 2.8.1`
```

**Comment by bastelfreak** [comment]
My personal recommendation is to not use the EoL Ruby 2.7. Now that PE LTS uses it doesn't make it easier...

For those unfortunate people I install an older version of faraday:
```
puppet resource package faraday ensure=2.8.1 provider=puppet_gem
```
