### ISSUE TITLE
Removal of obsolete multi_json dependency

### ISSUE THREAD

**Issue by graaff** [adrienthebo/r10k#1388]
The gemspec still contains a dependency on multi_json. This dependency was added in f7138d49dde3d3399b221f392f89701cf46e78e5 to support the use of faraday_middleware-multi_json, but the faraday dependencies are long gone and nothing else makes use of multi_json.

**Comment by nabertrand** [comment]
It looks like `multi_json` is still in the gemspec and ideally would be removed if no longer needed: https://github.com/puppetlabs/r10k/blob/8dd238fe3d3a4c69386348c73f5b8fca001b72fd/r10k.gemspec#L29
