### ISSUE TITLE
Minitar v1 has been released

### ISSUE THREAD

**Issue by halostatue** [adrienthebo/r10k#1398]
Minitar v1 has been released. R10k correctly uses `~> 0.9` for its dependency specification, but it incorrectly continues to use `Archive::Tar::Minitar`, which has been deprecated since 2017.

https://github.com/search?q=repo%3Apuppetlabs%2Fr10k+%28Archive%3A%3ATar%3A%3AMinitar+OR+minitar%29&type=code

There will be no further updates to v0.

**Comment by deric** [comment]
This is still an issue, `r10k` doesn't work with `minitar` `~> 1.0.0`
```
Installing minitar 1.0.2
Installing r10k 5.0.0
bundler: failed to load command: r10k (/builds/service/puppet-r10k/.bundle/ruby/3.2.0/bin/r10k)
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': cannot load such file -- archive/tar/minitar (LoadError)
```
