### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by raybellis** [adrienthebo/r10k#1409]
Can you please tag a new release?

The changes to the gemspec file in particular are causing problems on FreeBSD where the latest official 4.1.0 tagged release still refers to old versions of other packages that no longer exist in the FreeBSD package repository.

**Comment by raybellis** [comment]
Cross link back to my FreeBSD bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282466

**Comment by smortex** [comment]
I think we can relax the offending dependencies as a quick tests showed that allowing the latest version of puppet_forge and minitar seems to work as expected.  I will try to have a look this week to fill-in a PR.

**Comment by raybellis** [comment]
That's actually what I did to get mine working, apparently with no side effects, and indeed the latest gemspec file here had already done that.   The underlying issue for FreeBSD is that they usually only tend to package officially tagged releases.

**Comment by justinstoller** [comment]
We are working on a new release. It will bump our minimum Ruby version and thus be a major version bump. We're working out some additional changes that the community wanted to land as part of that major release and once those are ironed out we'll do a 5.0 release.

**Comment by justinstoller** [comment]
https://rubygems.org/gems/r10k/versions/5.0.0 Let me know if there's any issues with the new release!
